apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: khun431jb-python 
  janus-idp.io/tekton: khun431jb-python
  backstage.io/kubernetes-id: khun431jb-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: khun431jb-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  